# Limine v11 config. Boot straight into oxbow; no menu.
timeout: 0

/oxbow
    protocol: limine
    path: boot():/boot/oxbow
    # User-mode servers, delivered as modules. The kernel makes one process per
    # module, each in its own address space.
    module_path: boot():/boot/server.elf
    module_cmdline: pong
    module_path: boot():/boot/beta.elf
    module_cmdline: beta
    module_path: boot():/boot/hello.elf
    module_cmdline: hello
    module_path: boot():/boot/badge.elf
    module_cmdline: badge
    module_path: boot():/boot/kbd.elf
    module_cmdline: kbd
    module_path: boot():/boot/tty.elf
    module_cmdline: tty
    module_path: boot():/boot/shell.elf
    module_cmdline: shell
    module_path: boot():/boot/serial.elf
    module_cmdline: serial
