/* config.h for the oxbow libxkbcommon port (§48). Normally generated by meson;
 * hand-written here. We only ever compile a keymap from a STRING (the compositor
 * sends a full, self-contained keymap), so the XKB config-root / RMLVO defaults
 * are placeholders — the file-loading paths that use them are never executed. */
#ifndef OXBOW_XKB_CONFIG_H
#define OXBOW_XKB_CONFIG_H

#define LIBXKBCOMMON_VERSION "1.6.0"

#define DFLT_XKB_CONFIG_ROOT       "/usr/share/X11/xkb"
#define DFLT_XKB_CONFIG_EXTRA_PATH "/etc/xkb"
#define DEFAULT_XKB_RULES          "evdev"
#define DEFAULT_XKB_MODEL          "pc105"
#define DEFAULT_XKB_LAYOUT         "us"
#define DEFAULT_XKB_VARIANT        NULL
#define DEFAULT_XKB_OPTIONS        NULL

#define HAVE_UNISTD_H 1
#define HAVE___BUILTIN_EXPECT 1

/* HAVE_STRNDUP / HAVE_ASPRINTF / HAVE_VASPRINTF / HAVE_MMAP etc. are left unset:
 * utils.{c,h} provide portable fallbacks for those when the HAVE_ macro is off,
 * keeping the port self-contained (no extra libc surface). */

#endif /* OXBOW_XKB_CONFIG_H */
