#!/usr/bin/env python3
"""A minimal wayland-scanner: protocol XML -> client-header (.h) + private-code (.c).

Emits the same shape as upstream `wayland-scanner 1.22` (wl_proxy_marshal_flags
wrappers, wl_message tables, a per-protocol types[] array), but with the simpler —
and functionally identical — choice of giving every message its OWN contiguous
slice of types[] (no leading-NULL dedup; libwayland indexes types[] by arg position
and only dereferences object/new_id entries, so per-message slices are equivalent).

Built for the oxbow Wayland-app porting effort so we never need a Linux toolchain to
add a protocol. Reusable: `wl-scanner.py client-header foo.xml > foo.h` /
`wl-scanner.py private-code foo.xml > foo.c`.
"""
import sys, xml.etree.ElementTree as ET

# wayland arg type -> (signature char, C param type, is "typed" i.e. needs a types[] iface slot)
SIG = {'int':'i','uint':'u','fixed':'f','string':'s','object':'o','new_id':'n','array':'a','fd':'h'}
CTYPE = {'int':'int32_t','uint':'uint32_t','fixed':'wl_fixed_t','string':'const char *',
         'array':'struct wl_array *','fd':'int32_t'}

def args_of(msg):
    return [a for a in msg if a.tag == 'arg']

def since(msg):
    s = msg.get('since')
    return int(s) if s else 1

def signature(msg):
    s = ''
    sv = since(msg)
    if sv > 1:
        s += str(sv)
    for a in args_of(msg):
        if a.get('allow-null') == 'true':
            s += '?'
        s += SIG[a.get('type')]
    return s

def ctype_arg(a):
    t = a.get('type')
    if t in ('object','new_id'):
        iface = a.get('interface')
        return ('struct %s *' % iface) if iface else 'void *'
    return CTYPE[t]

def collect_interfaces(proto):
    return [i for i in proto if i.tag == 'interface']

def referenced_ifaces(proto, defined):
    """External interfaces (defined elsewhere) referenced by any object/new_id arg."""
    refs = set()
    for iface in collect_interfaces(proto):
        for msg in iface:
            if msg.tag not in ('request','event'): continue
            for a in args_of(msg):
                fi = a.get('interface')
                if fi and fi not in defined:
                    refs.add(fi)
    return sorted(refs)

def gen_code(proto):
    name = proto.get('name')
    out = []
    p = out.append
    p('/* Generated by oxbow tools/wl-scanner.py (wayland-scanner-compatible private-code) */')
    p('#include <stdlib.h>\n#include <stdint.h>\n#include "wayland-util.h"\n')
    p('#ifndef __has_attribute\n# define __has_attribute(x) 0\n#endif')
    p('#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)')
    p('#define WL_PRIVATE __attribute__ ((visibility("hidden")))\n#else\n#define WL_PRIVATE\n#endif\n')
    ifaces = collect_interfaces(proto)
    defined = {i.get('name') for i in ifaces}
    # Forward-declare EVERY interface used in types[] — external refs AND this
    # protocol's own (each is defined later in the file with WL_PRIVATE; an `extern`
    # forward decl before the types[] array that references them is required in C).
    for r in sorted(set(referenced_ifaces(proto, defined)) | defined):
        p('extern const struct wl_interface %s_interface;' % r)
    p('')
    # Build the per-protocol types[] array: each message contributes a contiguous
    # slice (one entry per arg: &iface for typed object/new_id else NULL).
    types = []          # list of 'NULL' or '&X_interface'
    msg_offset = {}     # id(msg) -> start offset in types[]
    def add_msg(msg):
        msg_offset[id(msg)] = len(types)
        for a in args_of(msg):
            fi = a.get('interface') if a.get('type') in ('object','new_id') else None
            types.append('&%s_interface' % fi if fi else 'NULL')
    for iface in ifaces:
        for msg in iface:
            if msg.tag in ('request','event'):
                add_msg(msg)
    p('static const struct wl_interface *%s_types[] = {' % name)
    if not types:
        p('\tNULL,')
    for t in types:
        p('\t%s,' % t)
    p('};\n')
    # wl_message tables + wl_interface per interface.
    for iface in ifaces:
        iname = iface.get('name')
        for kind, tag in (('requests','request'), ('events','event')):
            msgs = [m for m in iface if m.tag == tag]
            if not msgs: continue
            p('static const struct wl_message %s_%s[] = {' % (iname, kind))
            for m in msgs:
                off = msg_offset[id(m)]
                p('\t{ "%s", "%s", %s_types + %d },' % (m.get('name'), signature(m), name, off))
            p('};\n')
    for iface in ifaces:
        iname = iface.get('name'); ver = iface.get('version','1')
        reqs = [m for m in iface if m.tag == 'request']
        evs  = [m for m in iface if m.tag == 'event']
        rp = '%s_requests' % iname if reqs else 'NULL'
        ep = '%s_events' % iname if evs else 'NULL'
        p('WL_PRIVATE const struct wl_interface %s_interface = {' % iname)
        p('\t"%s", %s,' % (iname, ver))
        p('\t%d, %s,' % (len(reqs), rp))
        p('\t%d, %s,' % (len(evs), ep))
        p('};\n')
    return '\n'.join(out)

def upper(s): return s.upper()

def gen_header(proto):
    name = proto.get('name')
    out = []; p = out.append
    guard = upper(name) + '_CLIENT_PROTOCOL_H'
    p('/* Generated by oxbow tools/wl-scanner.py (wayland-scanner-compatible client-header) */')
    p('#ifndef %s\n#define %s\n' % (guard, guard))
    p('#include <stdint.h>\n#include <stddef.h>\n#include "wayland-client.h"\n')
    p('#ifdef __cplusplus\nextern "C" {\n#endif\n')
    ifaces = collect_interfaces(proto)
    defined = {i.get('name') for i in ifaces}
    # forward-declare every interface struct (this protocol's + referenced) and the iface externs.
    for r in referenced_ifaces(proto, defined):
        p('struct %s;' % r)
    for i in ifaces:
        p('struct %s;' % i.get('name'))
    p('')
    for i in ifaces:
        iname = i.get('name')
        p('#ifndef %s_INTERFACE\n#define %s_INTERFACE' % (upper(iname), upper(iname)))
        p('extern const struct wl_interface %s_interface;\n#endif' % iname)
    p('')
    for iface in ifaces:
        iname = iface.get('name')
        IN = upper(iname)
        # enums
        for en in [e for e in iface if e.tag == 'enum']:
            ename = en.get('name')
            p('#ifndef %s_%s_ENUM\n#define %s_%s_ENUM' % (IN, upper(ename), IN, upper(ename)))
            p('enum %s_%s {' % (iname, ename))
            for entry in [e for e in en if e.tag == 'entry']:
                p('\t%s_%s_%s = %s,' % (IN, upper(ename), upper(entry.get('name')), entry.get('value')))
            p('};\n#endif /* %s_%s_ENUM */\n' % (IN, upper(ename)))
        # event listener + add_listener
        evs = [m for m in iface if m.tag == 'event']
        if evs:
            p('struct %s_listener {' % iname)
            for ev in evs:
                params = ['void *data', 'struct %s *%s' % (iname, iname)]
                for a in args_of(ev):
                    params.append('%s %s' % (ctype_arg(ev_arg_listener(a)), a.get('name')))
                p('\tvoid (*%s)(%s);' % (ev.get('name'), ', '.join(params)))
            p('};\n')
            p('static inline int')
            p('%s_add_listener(struct %s *%s,' % (iname, iname, iname))
            p('\tconst struct %s_listener *listener, void *data)' % iname)
            p('{')
            p('\treturn wl_proxy_add_listener((struct wl_proxy *) %s,' % iname)
            p('\t\t(void (**)(void)) listener, data);\n}\n')
        # opcode #defines (requests)
        reqs = [m for m in iface if m.tag == 'request']
        for op, r in enumerate(reqs):
            p('#define %s_%s %d' % (IN, upper(r.get('name')), op))
        if reqs: p('')
        # set_user_data / get_user_data / get_version / destroy boilerplate
        p('static inline void')
        p('%s_set_user_data(struct %s *%s, void *user_data)' % (iname, iname, iname))
        p('{\n\twl_proxy_set_user_data((struct wl_proxy *) %s, user_data);\n}' % iname)
        p('static inline void *')
        p('%s_get_user_data(struct %s *%s)' % (iname, iname, iname))
        p('{\n\treturn wl_proxy_get_user_data((struct wl_proxy *) %s);\n}' % iname)
        p('static inline uint32_t')
        p('%s_get_version(struct %s *%s)' % (iname, iname, iname))
        p('{\n\treturn wl_proxy_get_version((struct wl_proxy *) %s);\n}' % iname)
        # request wrappers
        has_destructor = False
        for op, r in enumerate(reqs):
            rargs = args_of(r)
            newids = [a for a in rargs if a.get('type') == 'new_id']
            is_destructor = (r.get('type') == 'destructor')
            if is_destructor: has_destructor = True
            params = ['struct %s *%s' % (iname, iname)]
            for a in rargs:
                if a.get('type') == 'new_id': continue
                params.append('%s %s' % (ctype_arg(a), a.get('name')))
            flags = 'WL_MARSHAL_FLAG_DESTROY' if is_destructor else '0'
            ver = 'wl_proxy_get_version((struct wl_proxy *) %s)' % iname
            opc = '%s_%s' % (IN, upper(r.get('name')))
            if newids and newids[0].get('interface'):
                ni = newids[0].get('interface')
                p('static inline struct %s *' % ni)
                p('%s_%s(%s)' % (iname, r.get('name'), ', '.join(params)))
                p('{\n\tstruct wl_proxy *id;')
                varargs = []
                for a in rargs:
                    varargs.append('NULL' if a.get('type') == 'new_id' else a.get('name'))
                tail = (', ' + ', '.join(varargs)) if varargs else ''
                p('\tid = wl_proxy_marshal_flags((struct wl_proxy *) %s,' % iname)
                p('\t\t%s, &%s_interface, %s, %s%s);' % (opc, ni, ver, flags, tail))
                p('\treturn (struct %s *) id;\n}\n' % ni)
            else:
                p('static inline void')
                p('%s_%s(%s)' % (iname, r.get('name'), ', '.join(params)))
                p('{')
                varargs = [a.get('name') for a in rargs]
                tail = (', ' + ', '.join(varargs)) if varargs else ''
                p('\twl_proxy_marshal_flags((struct wl_proxy *) %s,' % iname)
                p('\t\t%s, NULL, %s, %s%s);\n}\n' % (opc, ver, flags, tail))
    p('#ifdef __cplusplus\n}\n#endif\n')
    p('#endif')
    return '\n'.join(out)

def ev_arg_listener(a):
    # events deliver new_id args as a concrete object pointer to the client.
    return a

def server_req_ctype(a):
    """Type of a request-handler vtable param (server side): objects and new_ids
    arrive as/for wl_resource; new_id is the raw id (uint32_t)."""
    t = a.get('type')
    if t == 'object':
        return 'struct wl_resource *'
    if t == 'new_id':
        # A new_id whose interface is NOT statically known (generic bind) also carries
        # interface name + version strings, but libwayland delivers just the id here.
        return 'uint32_t'
    return CTYPE[t]

def server_ev_ctype(a):
    """Type of an event send-helper param (server side): objects/new_ids are resources."""
    t = a.get('type')
    if t in ('object', 'new_id'):
        return 'struct wl_resource *'
    return CTYPE[t]

def gen_server_header(proto):
    """Server-side header: the same wl_interface externs + enums as the client header,
    but a request-handler vtable (struct <iface>_interface) and wl_resource_post_event
    event senders instead of proxy request wrappers. Matches wayland-scanner's shape
    closely enough for libweston (which implements the server side)."""
    name = proto.get('name')
    out = []; p = out.append
    guard = upper(name) + '_SERVER_PROTOCOL_H'
    p('/* Generated by oxbow tools/wl-scanner.py (wayland-scanner-compatible server-header) */')
    p('#ifndef %s\n#define %s\n' % (guard, guard))
    p('#include <stdint.h>\n#include <stddef.h>\n#include "wayland-server.h"\n')
    p('#ifdef __cplusplus\nextern "C" {\n#endif\n')
    p('struct wl_client;\nstruct wl_resource;\n')
    ifaces = collect_interfaces(proto)
    defined = {i.get('name') for i in ifaces}
    for r in referenced_ifaces(proto, defined):
        p('struct %s;' % r)
    for i in ifaces:
        p('struct %s;' % i.get('name'))
    p('')
    for i in ifaces:
        iname = i.get('name')
        p('#ifndef %s_INTERFACE\n#define %s_INTERFACE' % (upper(iname), upper(iname)))
        p('extern const struct wl_interface %s_interface;\n#endif' % iname)
    p('')
    for iface in ifaces:
        iname = iface.get('name'); IN = upper(iname)
        # enums (identical to the client header)
        for en in [e for e in iface if e.tag == 'enum']:
            ename = en.get('name')
            p('#ifndef %s_%s_ENUM\n#define %s_%s_ENUM' % (IN, upper(ename), IN, upper(ename)))
            p('enum %s_%s {' % (iname, ename))
            for entry in [e for e in en if e.tag == 'entry']:
                p('\t%s_%s_%s = %s,' % (IN, upper(ename), upper(entry.get('name')), entry.get('value')))
            p('};\n#endif /* %s_%s_ENUM */\n' % (IN, upper(ename)))
            # per-entry since-version defines (wayland-scanner emits these for entries
            # carrying a `since` attribute; libweston may gate on them)
            for entry in [e for e in en if e.tag == 'entry']:
                sv = entry.get('since')
                if sv:
                    p('#define %s_%s_%s_SINCE_VERSION %s' %
                      (IN, upper(ename), upper(entry.get('name')), sv))
            if any(e.get('since') for e in en if e.tag == 'entry'):
                p('')
        reqs = [m for m in iface if m.tag == 'request']
        evs = [m for m in iface if m.tag == 'event']
        # request-handler vtable (what the compositor fills in)
        if reqs:
            p('struct %s_interface {' % iname)
            for r in reqs:
                params = ['struct wl_client *client', 'struct wl_resource *resource']
                for a in args_of(r):
                    params.append('%s %s' % (server_req_ctype(a).rstrip(), a.get('name')))
                p('\tvoid (*%s)(%s);' % (r.get('name'), ', '.join(params)))
            p('};\n')
        # event opcodes
        for op, ev in enumerate(evs):
            p('#define %s_%s %d' % (IN, upper(ev.get('name')), op))
        if evs: p('')
        # SINCE_VERSION (requests then events)
        for r in reqs:
            p('#define %s_%s_SINCE_VERSION %d' % (IN, upper(r.get('name')), since(r)))
        for ev in evs:
            p('#define %s_%s_SINCE_VERSION %d' % (IN, upper(ev.get('name')), since(ev)))
        if reqs or evs: p('')
        # event senders: wl_resource_post_event(resource_, OPCODE, args...)
        for ev in evs:
            params = ['struct wl_resource *resource_']
            for a in args_of(ev):
                params.append('%s %s' % (server_ev_ctype(a).rstrip(), a.get('name')))
            p('static inline void')
            p('%s_send_%s(%s)' % (iname, ev.get('name'), ', '.join(params)))
            p('{')
            argnames = [a.get('name') for a in args_of(ev)]
            tail = (', ' + ', '.join(argnames)) if argnames else ''
            p('\twl_resource_post_event(resource_, %s_%s%s);' % (IN, upper(ev.get('name')), tail))
            p('}\n')
    p('#ifdef __cplusplus\n}\n#endif\n')
    p('#endif')
    return '\n'.join(out)

def main():
    mode, path = sys.argv[1], sys.argv[2]
    proto = ET.parse(path).getroot()
    if mode == 'client-header':
        sys.stdout.write(gen_header(proto))
    elif mode == 'server-header':
        sys.stdout.write(gen_server_header(proto))
    else:
        sys.stdout.write(gen_code(proto))
    sys.stdout.write('\n')

if __name__ == '__main__':
    main()
